__asm__(
".text \n"
".global " START "\n"
".type " START ",%function\n"
START ":\n"
"	mov x29, #0\n"
"	mov x30, #0\n"
#ifdef LIBSHIM
"	mov x0, sp\n"
"	cvtd c0, x0\n"
"	bl do_raw_args_marshalling\n"
"	mov csp, c0\n"
#endif
"	bl __morello_init_static\n"
"	mov c0, csp\n"
".weak _DYNAMIC\n"
".hidden _DYNAMIC\n"
"	adrp c1, _DYNAMIC\n"
"	add c1, c1, #:lo12:_DYNAMIC\n"
"	alignd csp, csp, #4\n"
"	b " START "_c\n"
);

__asm__ (".text \n"
".global __morello_init_static\n"
".type __morello_init_static,%function\n"
"__morello_init_static:\n"
"	ldr     x10, [c0], #32\n" //Increment argc/NULL
"	add     c0, c0, x10, lsl #4\n"
".Lloop_get_auxv:\n"
"	ldr     c9, [c0], #16\n"
"	cmp     c9, czr\n"
"	b.ne	.Lloop_get_auxv\n"
".Lloop_auxv:\n"
"	ldp     x9, xzr, [c0], #16\n"
"	cmp     x9, xzr\n"
"	b.eq    .Lreloc_start\n"
"	cmp     x9, #60\n" //AT_CHERI_EXEC_RW_CAP
"	b.eq    .Lload_cap_rw\n"
"	add     c0, c0, #16\n"
"	b       .Lloop_auxv\n"
".Lload_cap_rw:\n"
"	ldr     c11, [c0], #16\n"
".Lreloc_start:\n"
"	adrp    c0, __cap_relocs_start\n"
"	add     c0, c0, :lo12:__cap_relocs_start\n"
"	adrp    c1, __cap_relocs_end\n"
"	add     c1, c1, :lo12:__cap_relocs_end\n"
"1:\n"
"	cmp     c0, c1\n"
"	b.eq    2f\n"
"	ldr     x2, [c0, #0]\n"
"	cvt     c2, c11, x2\n" //Use RW cap for location
"	ldp     x3, x4, [c0, #8]\n"
"	ldp     x5, x6, [c0, #24]\n"
"	ands    x7, x6, #0x8000000000000000\n"
"	b.ne    .Lcap_pcc\n"
".Lcap_rw:\n"
"	cvt     c3, c11, x3\n"
"	b       .Lpcap\n"
".Lcap_pcc:\n"
"	cvtp	c3, x3\n"
".Lpcap:\n"
"	scbndse c3, c3, x5\n"
"	add     c3, c3, x4\n"
"	orr     x6, x6, #~(0b111111111111111111)\n"
"	clrperm c3, c3, x6\n"
"	str     c3, [c2]\n"
"	add     c0, c0, #40\n"
"	b       1b\n"
"2:\n"
"	ret\n");
