#pragma once

#define READ_CAP_PERMS	(	__CHERI_CAP_PERMISSION_PERMIT_LOAD__ | \
							__CHERI_CAP_PERMISSION_PERMIT_LOAD_CAPABILITY__ | \
							__ARM_CAP_PERMISSION_MUTABLE_LOAD__)

#define WRITE_CAP_PERMS	(	__CHERI_CAP_PERMISSION_PERMIT_STORE__ | \
							__CHERI_CAP_PERMISSION_PERMIT_STORE_CAPABILITY__ | \
							__CHERI_CAP_PERMISSION_PERMIT_STORE_LOCAL__)

#define EXEC_CAP_PERMS	(	__CHERI_CAP_PERMISSION_PERMIT_EXECUTE__ | \
							__ARM_CAP_PERMISSION_EXECUTIVE__ | \
							__CHERI_CAP_PERMISSION_ACCESS_SYSTEM_REGISTERS__)

#define ROOT_CAP_PERMS	(	__CHERI_CAP_PERMISSION_GLOBAL__ | \
							__ARM_CAP_PERMISSION_BRANCH_SEALED_PAIR__)

#define SEAL_CAP_PERMS	(	__CHERI_CAP_PERMISSION_GLOBAL__ | \
							__CHERI_CAP_PERMISSION_PERMIT_SEAL__ | \
							__CHERI_CAP_PERMISSION_PERMIT_UNSEAL__)

