#pragma once

static const unsigned long READ_CAP_PERMS =
#ifdef __ARM_CAP_PERMISSION_MUTABLE_LOAD__
							__ARM_CAP_PERMISSION_MUTABLE_LOAD__ |
#endif
							__CHERI_CAP_PERMISSION_PERMIT_LOAD__ |
							__CHERI_CAP_PERMISSION_PERMIT_LOAD_CAPABILITY__;

static unsigned long WRITE_CAP_PERMS =
							__CHERI_CAP_PERMISSION_PERMIT_STORE__ |
							__CHERI_CAP_PERMISSION_PERMIT_STORE_CAPABILITY__ |
							__CHERI_CAP_PERMISSION_PERMIT_STORE_LOCAL__;

static unsigned long EXEC_CAP_PERMS =
#ifdef __ARM_CAP_PERMISSION_EXECUTIVE__
							__ARM_CAP_PERMISSION_EXECUTIVE__ |
#endif
							__CHERI_CAP_PERMISSION_PERMIT_EXECUTE__ |
							__CHERI_CAP_PERMISSION_ACCESS_SYSTEM_REGISTERS__;

static unsigned long ROOT_CAP_PERMS =
#ifdef __ARM_CAP_PERMISSION_BRANCH_SEALED_PAIR__
							__ARM_CAP_PERMISSION_BRANCH_SEALED_PAIR__ |
#endif
							__CHERI_CAP_PERMISSION_GLOBAL__;

static unsigned long SEAL_CAP_PERMS =
							__CHERI_CAP_PERMISSION_GLOBAL__ |
							__CHERI_CAP_PERMISSION_PERMIT_SEAL__ |
							__CHERI_CAP_PERMISSION_PERMIT_UNSEAL__;
