stages:
  - build
  - test
  - toolchain

variables:
  MORELLOIE_VERSION: 2.3-533
  MORELLOIE_DOWNLOAD_URL: https://developer.arm.com/-/media/Arm%20Developer%20Community/Downloads/Morello/Development%20Tools/Morello%20Instruction%20Emulator
  MORELLO_LLVM_VERSION: '1.7'
  LLVM_BRANCH: "morello/dev"
  LLVM_VERSION: "dev"

build-musl-aarch64-llvm:
  image: ${CI_REGISTRY}/morello/morello-ci-restricted-containers/morello-morelloie:latest.arm64
  stage: build
  script:
    - /bin/bash .gitlab/build-aarch64-llvm.sh
  tags:
    - arm64
  artifacts:
    when: always
    paths:
      - "test/*.xml"
      - "test/morello-musl-tests-purecap.tar.gz"
    expire_in: 15 days
    reports:
      junit:
        - ${CI_PROJECT_DIR}/test/*.xml

build-musl-x86-llvm:
  image: ${CI_REGISTRY}/morello/morello-ci-restricted-containers/morello-morelloie:latest.amd64
  stage: build
  script:
    - /bin/bash .gitlab/build-x86-llvm.sh

build-toolchain-aarch64:
  image: ${CI_REGISTRY}/morello/morello-ci-restricted-containers/morello-morelloie:latest.arm64
  variables:
    LLVM_TARGETS: "AArch64"
    LLVM_TEST_REPORT: "llvm-test-results-aarch64.xml"
    BUNDLE_NAME: "llvm-morello-linux-aarch64"
  stage: toolchain
  allow_failure: true
  needs: []
  script:
    - /bin/bash .gitlab/build-toolchain.sh
  tags:
    - arm64_fast
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  artifacts:
    when: always
    paths:
      - "clang/*clang*.tar.gz"
      - "clang/*.xml"
    expire_in: 15 days

build-toolchain-x86:
  image: ${CI_REGISTRY}/morello/morello-ci-restricted-containers/morello-morelloie:latest.amd64
  variables:
    LLVM_TARGETS: "X86;AArch64"
    LLVM_TEST_REPORT: "llvm-test-results-x86.xml"
    BUNDLE_NAME: "llvm-morello-linux-x86"
  stage: toolchain
  allow_failure: true
  needs: []
  script:
    - /bin/bash .gitlab/build-toolchain.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  artifacts:
    when: always
    paths:
      - "clang/*clang*.tar.gz"
      - "clang/*.xml"
    expire_in: 15 days

test-morello-examples:
  image: ${CI_REGISTRY}/morello/morello-ci-restricted-containers/morello-morelloie:latest.arm64
  variables:
    MORELLO_EXAMPLES_BRANCH: "main"
  stage: test
  needs: []
  script:
    - /bin/bash .gitlab/test-morello-examples.sh
  tags:
    - arm64
