#define RESTRICT_BNDS_IF_MORELLO(c, w) c
#define RESTRICT_BNDS_IF_MORELLO_SUBOBJ(c, w) c

#ifdef MORELLO

#undef RESTRICT_BNDS_IF_MORELLO
#define RESTRICT_BNDS_IF_MORELLO(c, w) __builtin_cheri_bounds_set(c, w)

#ifdef MORELLO_ENABLE_SUBOBJECT_BOUNDS

#undef RESTRICT_BNDS_IF_MORELLO_SUBOBJ
#define RESTRICT_BNDS_IF_MORELLO_SUBOBJ(c, w) RESTRICT_BNDS_IF_MORELLO(c, w)

#endif // MORELLO_ENABLE_SUBOBJECT_BOUNDS

#endif // MORELLO
